/**
 * Katalog kode error aplikasi.
 * Kode ini bagian dari kontrak API — jangan diubah tanpa memperbarui klien.
 */
export const ERROR_CODES = {
  // umum
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',

  // auth
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',

  // event
  EVENT_NOT_OPEN: 'EVENT_NOT_OPEN',
  EVENT_CLOSED: 'EVENT_CLOSED',
  EVENT_PAUSED: 'EVENT_PAUSED',
  OUTSIDE_SERVICE_HOURS: 'OUTSIDE_SERVICE_HOURS',

  // public page
  PAGE_NOT_PUBLISHED: 'PAGE_NOT_PUBLISHED',
  REGISTRATION_DISABLED: 'REGISTRATION_DISABLED',
  QUEUE_TYPE_UNAVAILABLE: 'QUEUE_TYPE_UNAVAILABLE',
  DAILY_LIMIT_REACHED: 'DAILY_LIMIT_REACHED',
  CAPTCHA_REQUIRED: 'CAPTCHA_REQUIRED',
  CAPTCHA_INVALID: 'CAPTCHA_INVALID',
  /** Pengunjung berada di luar radius pagar lokasi halaman publik (§36). */
  OUTSIDE_GEOFENCE: 'OUTSIDE_GEOFENCE',

  // queue
  QUEUE_NOT_FOUND: 'QUEUE_NOT_FOUND',
  QUEUE_LIMIT_REACHED: 'QUEUE_LIMIT_REACHED',
  QUEUE_ALREADY_CALLED: 'QUEUE_ALREADY_CALLED',
  QUEUE_ALREADY_FINISHED: 'QUEUE_ALREADY_FINISHED',
  QUEUE_INVALID_TRANSITION: 'QUEUE_INVALID_TRANSITION',
  QUEUE_EMPTY: 'QUEUE_EMPTY',
  QUEUE_NUMBER_GENERATION_FAILED: 'QUEUE_NUMBER_GENERATION_FAILED',
  RECALL_LIMIT_REACHED: 'RECALL_LIMIT_REACHED',

  // testimoni
  RATING_DISABLED: 'RATING_DISABLED',

  // operator
  NOT_ASSIGNED: 'NOT_ASSIGNED',
  OPERATOR_ALREADY_SEATED: 'OPERATOR_ALREADY_SEATED',
  COUNTER_HAS_NO_SERVICE: 'COUNTER_HAS_NO_SERVICE',
  NO_ACTIVE_QUEUE: 'NO_ACTIVE_QUEUE',

  // integrasi data source
  DATA_SOURCE_UNREACHABLE: 'DATA_SOURCE_UNREACHABLE',
  DATA_SOURCE_INVALID_RESPONSE: 'DATA_SOURCE_INVALID_RESPONSE',
  DATA_SOURCE_DISABLED: 'DATA_SOURCE_DISABLED',
  AUTOFILL_NOT_FOUND: 'AUTOFILL_NOT_FOUND',

  // display
  DISPLAY_NOT_FOUND: 'DISPLAY_NOT_FOUND',
  DISPLAY_TOKEN_INVALID: 'DISPLAY_TOKEN_INVALID',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
